
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - workshop.example.com
  resources:
  - custommysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workshop.example.com
  resources:
  - custommysqls/finalizers
  verbs:
  - update
- apiGroups:
  - workshop.example.com
  resources:
  - custommysqls/status
  verbs:
  - get
  - patch
  - update
